### ISSUE TITLE
Adplayer pod issue

### ISSUE THREAD

**Issue by piyushtour** [Aniview/ad-player-sdk-ios-pods#2]
Adplayer sdk Batch.o file generate duplicate symbol issue
It is conflict with Batch SDK. 

![Screenshot 2023-12-21 at 5 21 46 PM](https://github.com/Aniview/ad-player-sdk-ios-pods/assets/109497664/93868215-b332-448b-a9ad-0c3d15a72a95)

tried all versions
pod 'AdPlayerSDK', '~> 1.8.1' 

pod 'AdPlayerSDK', '~> 1.8.0'

pod 'AdPlayerSDK', '~> 1.7.3'

Please share solution @pavlo-yevtukhov

**Comment by serhiivpolishchuk** [comment]
@piyushtour please contact us in slack channel or on email: serhii.v.polishchuk@globallogic.com.
So we can close the issues faster and inform you immediatelly.

**Comment by piyushtour** [comment]
@serhiivpolishchuk  Above issue resolved in 'AdPlayerSDK', '~> 1.9.0'
