### ISSUE TITLE
Ads Close Event not working

### ISSUE THREAD

**Issue by piyushtour** [Aniview/ad-player-sdk-ios-pods#3]
![Screenshot 2024-01-19 at 12 08 43 PM](https://github.com/Aniview/ad-player-sdk-ios-pods/assets/109497664/5e8376c7-1b21-46b2-9f23-2a1d50542a03)

How to get close ads Event? 

I used this but it is not working  - "AdPlayerEventType.closed"

@pavlo-yevtukhov

**Comment by pavlo-yevtukhov** [comment]
Hi @piyushtour, 
Thanks for pointing it out. I will look into it.

Also, it would be great to discuss it in more detail.
Could you please reach out to me (or Aniview team) on Slack / Email?

**Comment by pavlo-yevtukhov** [comment]
Hi @piyushtour 
This was addressed in `1.9.4`

**Comment by piyushtour** [comment]
Thanx @pavlo-yevtukhov
